export const STAFF_USERS = "STAFF_USERS"
export const STAFFUSER_SUCCESS = "STAFFUSER_SUCCESS"
export const GET_STAFFUSER = "GET_STAFFUSER"
export const GET_STAFFUSER_SUCCESS = "GET_STAFFUSER_SUCCESS"
export const GET_STAFFUSER_FAIL = "GET_STAFFUSER_FAIL"

