// Get LIST
export const GET_ADMIN_USER = "GET_ADMIN_USER"
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS"

// Add NEW USER
export const ADD_NEW_USER = "ADD_NEW_USER"
export const ADD_ADMIN_USER_SUCCESS = "ADD_ADMIN_USER_SUCCESS"
// export const ADD_USER_FAIL = "ADD_USER_FAIL"
