// Get LIST
export const GET_ADMIN_USER = "GET_ADMIN_USER"
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS"
export const GET_ADMIN_FAIL = "GET_ADMIN_FAIL"

// Add NEW USER

export const ADD_ADMIN_DATA = "ADD_ADMIN_DATA"
export const ADD_ADMIN_DATA_SUCCESS = "ADD_ADMIN_DATA_SUCCESS"
