export const ADD_CREATE_DETAIL_SUCCESS = "ADD_CREATE_DETAIL_SUCCESS"
export const ADD_NEW_CREATE_DETAIL = "ADD_NEW_CREATE_DETAIL"

export const GET_CREATE_TICKET = "GET_CREATE_TICKET"
export const GET_CREATE_TICKET_SUCCESS = "GET_CREATE_TICKET_SUCCESS"
