export const ADMIN_USERS = "ADMIN_USERS"
export const ADMINUSER_SUCCESS = "ADMINUSER_SUCCESS"
export const GET_ADMINUSER = "GET_ADMINUSER"
export const GET_ADMINUSER_SUCCESS = "GET_ADMINUSER_SUCCESS"
export const GET_ADMINUSER_FAIL = "GET_ADMINUSER_FAIL"
export const GET_USERDROPDOWN = "GET_USERDROPDOWN"
export const GET_USERDROPDOWN_SUCCESS = "GET_USERDROPDOWN_SUCCESS"
export const GET_USERDROPDOWN_FAIL = "GET_USERDROPDOWN_FAIL"

