export const ADMIN_USERS = "ADMIN_USERS"
export const ADMINUSER_SUCCESS = "ADMINUSER_SUCCESS"
export const GET_ADMINUSER = "GET_ADMINUSER"
export const GET_ADMINUSER_SUCCESS = "GET_ADMINUSER_SUCCESS"
export const GET_ADMINUSER_FAIL = "GET_ADMINUSER_FAIL"

